options:
  typescript:
    rewriteImports: true
  uglify:
    ecma: 8
    compress:
      sequences: true
      properties: true
      dead_code: true
      drop_debugger: true
      unsafe: true
      unsafe_comps: true
      unsafe_Func: true
      unsafe_math: true
      unsafe_proto: true
      unsafe_regexp: true
      conditionals: true
      comparisons: true
      evaluate: true
      booleans: true
      typeofs: true
      loops: true
      unused: true
      toplevel: false
      top_retain: []
      hoist_funs: false
      hoist_vars: false
      if_return: true
      inline: true
      join_vars: false
      cascade: true
      collapse_vars: true
      reduce_vars: true
      warnings: false
      negate_iife: false
      pure_getters: false
      pure_funcs: null
      drop_console: true
      expression: true
      keep_fargs: false
      keep_fnames: true
      passes: 1
      keep_infinity: true
      side_effects: true
    mangle:
      reserved: []
      toplevel: false
      properties: false
      keep_fnames: true
      eval: true
    parse:
      bare_returns: false
      html5_comments: true
      shebang: false
    output:
      ascii_only: false
      beautify: false
      bracketize: false
      comments: some
      indent_level: 4
      indent_start: 0
      inline_script: true
      keep_quoted_props: false
      max_line_len: 1024
      preamble: null
      preserve_line: false
      quote_keys: false
      quote_style: 0
      semicolons: true
      shebang: false
      width: 80
      wrap_iife: false
    nameCache: {}
